kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployexample
spec:
  replicas: 4
  template:
    metadata: 
      labels:
        app: frontend
    spec:
      containers:
      - name: container1
        image: aamirpinger/helloworld
        imagePullPolicy: IfNotPresent
